$background = 0c0f0b
$onBackground = e0e8db
$surface = 0c0f0b
$surfaceDim = 0c0f0b
$surfaceBright = 272e26
$surfaceContainerLowest = 000000
$surfaceContainerLow = 10150f
$surfaceContainer = 161b15
$surfaceContainerHigh = 1b211a
$surfaceContainerHighest = 212820
$onSurface = e0e8db
$surfaceVariant = 212820
$onSurfaceVariant = a6ada2
$outline = 70786d
$outlineVariant = 434a41
$inverseSurface = f8faf3
$inverseOnSurface = 535650
$shadow = 000000
$scrim = 000000
$surfaceTint = add0a8
$primary = add0a8
$primaryDim = 9fc29b
$onPrimary = 294729
$primaryContainer = 3b5a3a
$onPrimaryContainer = c9edc4
$inversePrimary = 476746
$primaryFixed = c8ecc3
$primaryFixedDim = badeb6
$onPrimaryFixed = 284629
$onPrimaryFixedVariant = 446343
$secondary = b9ccb4
$secondaryDim = abbea7
$onSecondary = 344433
$secondaryContainer = 2f3f2e
$onSecondaryContainer = b2c4ad
$secondaryFixed = d5e8cf
$secondaryFixedDim = c7dac2
$onSecondaryFixed = 334332
$onSecondaryFixedVariant = 4f604d
$tertiary = fafebb
$tertiaryDim = e3e7a6
$onTertiary = 5e622e
$tertiaryContainer = ebf0ad
$onTertiaryContainer = 565a27
$tertiaryFixed = f1f6b3
$tertiaryFixedDim = e3e7a6
$onTertiaryFixed = 474b19
$onTertiaryFixedVariant = 646833
$error = f97758
$errorDim = c44f34
$onError = 450900
$errorContainer = 85230a
$onErrorContainer = ff9b82
$primaryPaletteKeyColor = 5f7f5d
$secondaryPaletteKeyColor = 6a7c67
$tertiaryPaletteKeyColor = 767b44
$neutralPaletteKeyColor = 757872
$neutralVariantPaletteKeyColor = 72796f
$errorPaletteKeyColor = c75236
$primary_paletteKeyColor = 5f7f5d
$secondary_paletteKeyColor = 6a7c67
$tertiary_paletteKeyColor = 767b44
$neutral_paletteKeyColor = 757872
$neutral_variant_paletteKeyColor = 72796f
$term0 = 343433
$term1 = 7e9c00
$term2 = 9bdd81
$term3 = c1f58e
$term4 = 84b693
$term5 = c6a844
$term6 = a0d79e
$term7 = d4dbc7
$term8 = a0a595
$term9 = 92b600
$term10 = a2f185
$term11 = dcffbb
$term12 = acc8ae
$term13 = cec06b
$term14 = aeeaa8
$term15 = ffffff
$rosewater = f2f2e4
$flamingo = e3e4c5
$pink = ffd79d
$mauve = 5bd0df
$red = c5b542
$maroon = c6c177
$peach = bfd695
$yellow = e4f8cf
$green = b1efad
$teal = b2edbe
$sky = a5eabe
$sapphire = 85d8ad
$blue = 69cfaa
$lavender = 89dcc6
$klink = 289870
$klinkSelection = 279871
$kvisited = 008ca9
$kvisitedSelection = 008ca9
$knegative = 838f00
$knegativeSelection = 838f00
$kneutral = 88ba13
$kneutralSelection = 87ba15
$kpositive = 54be63
$kpositiveSelection = 53be64
$text = e0e8db
$subtext1 = a6ada2
$subtext0 = 70786d
$overlay2 = 62695f
$overlay1 = 535950
$overlay0 = 454b43
$surface2 = 383d36
$surface1 = 2a2e28
$surface0 = 1b1f1a
$base = 0c0f0b
$mantle = 0c0f0b
$crust = 0b0e0a
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
