$background = 121411
$onBackground = e2e3dd
$surface = 121411
$surfaceDim = 121411
$surfaceBright = 373a36
$surfaceContainerLowest = 0c0f0c
$surfaceContainerLow = 1a1c19
$surfaceContainer = 1e201d
$surfaceContainerHigh = 282b27
$surfaceContainerHighest = 333532
$onSurface = e2e3dd
$surfaceVariant = 424940
$onSurfaceVariant = c2c9bd
$outline = 8c9388
$outlineVariant = 424940
$inverseSurface = e2e3dd
$inverseOnSurface = 2f312d
$shadow = 000000
$scrim = 000000
$surfaceTint = a5d2a1
$primary = a5d2a1
$primaryDim = cefdc9
$onPrimary = 103815
$primaryContainer = 729d70
$onPrimaryContainer = 093310
$inversePrimary = 3f6840
$primaryFixed = c0efbc
$primaryFixedDim = a5d2a1
$onPrimaryFixed = 002106
$onPrimaryFixedVariant = 284f2a
$secondary = b9ccb4
$secondaryDim = d5e8cf
$onSecondary = 253424
$secondaryContainer = 3d4d3b
$onSecondaryContainer = abbea7
$secondaryFixed = d5e8cf
$secondaryFixedDim = b9ccb4
$onSecondaryFixed = 101f10
$onSecondaryFixedVariant = 3b4b39
$tertiary = 92d0e6
$tertiaryDim = a2e0f7
$onTertiary = 003543
$tertiaryContainer = 5d9bb0
$onTertiaryContainer = 00303c
$tertiaryFixed = b5ebff
$tertiaryFixedDim = 92d0e6
$onTertiaryFixed = 001f28
$onTertiaryFixedVariant = 004e60
$error = ffb4ab
$errorDim = ff554a
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryPaletteKeyColor = 578156
$secondaryPaletteKeyColor = 6a7c67
$tertiaryPaletteKeyColor = 5d9bb0
$neutralPaletteKeyColor = 767873
$neutralVariantPaletteKeyColor = 72796f
$errorPaletteKeyColor = de3730
$primary_paletteKeyColor = 578156
$secondary_paletteKeyColor = 6a7c67
$tertiary_paletteKeyColor = 5d9bb0
$neutral_paletteKeyColor = 767873
$neutral_variant_paletteKeyColor = 72796f
$term0 = 343433
$term1 = 7e9c00
$term2 = 9bdd80
$term3 = c2f58e
$term4 = 84b693
$term5 = c6a844
$term6 = a0d79e
$term7 = d4dbc7
$term8 = a0a595
$term9 = 92b600
$term10 = a2f185
$term11 = ddffbb
$term12 = acc8ad
$term13 = cec06b
$term14 = aeeaa8
$term15 = ffffff
$rosewater = f2f2e4
$flamingo = e3e4c5
$pink = ffd79d
$mauve = 5bd0df
$red = c5b542
$maroon = c6c177
$peach = bfd695
$yellow = e4f8cf
$green = b1efad
$teal = b3edbe
$sky = a5eabe
$sapphire = 85d8ad
$blue = 69cfaa
$lavender = 89dcc6
$klink = 289871
$klinkSelection = 279871
$kvisited = 008ca9
$kvisitedSelection = 008ca9
$knegative = 838f00
$knegativeSelection = 838f00
$kneutral = 87ba14
$kneutralSelection = 87ba15
$kpositive = 53be64
$kpositiveSelection = 53be64
$text = e2e3dd
$subtext1 = c2c9bd
$subtext0 = 8c9388
$overlay2 = 7a8076
$overlay1 = 676c64
$overlay0 = 565b54
$surface2 = 464a43
$surface1 = 353833
$surface0 = 232622
$base = 121411
$mantle = 121411
$crust = 111310
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
